export const SHOW_STATUS_INPUT = 'SHOW_STATUS_INPUT';
export const HIDE_STATUS_INPUT = 'HIDE_STATUS_INPUT';
export const SAVE_STATUS = 'SAVE_STATUS';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const CHANGE_ALERT = 'CHANGE_ALERT';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';